---
# This is a sample database file for the DataMapper ORM
development: &defaults
  # These are the settings for repository :default
  adapter:  mysql
  database: ambernet_development
  username: ambernet_db
  password: tuwd7n
  host:     localhost
  socket:   /tmp/mysql.sock
 
  # Add more repositories
  # repositories:
  #   repo1:
  #     adapter:  sqlite3
  #     database: sample_1_development.db
  #   repo2:
  #     ...
 
staging:
  <<:       *defaults
  database: ambernet_staging
  username: mdolian_db
  password: tuwd7n
  host:     mysql50-staging-1
  
rake:
  <<: *defaults